name: Részvény elemzés

on:
  schedule:
       - cron: '0 20 * * 6'        # szombat 20:00 UTC (hetente)


jobs:
  run-stock-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klónozása
        uses: actions/checkout@v3

      - name: Python telepítése
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Csomagok telepítése
        run: |
          python -m pip install --upgrade pip
          pip install yahoo_fin pandas numpy

      - name: Elemző script futtatása
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python Reszvenygyertyajelek.py
